### ISSUE TITLE
PAC-Man Website

### ISSUE THREAD

**Issue by metaiiica** [PAC-ROM/android_vendor_pac#58]
I have buyed a Domain called http://pac-man-rom.de for my builds and little more. But i think, this is a good idea for made a global Site for FAQ, Helpdesk (globally), embedded Chat, Device-Infos, Downloadlinks from all officially Devices and many more... 
I can install a Wordpress or other so we can build a nice Site. All have Access was here in the List....

**Comment by Nick0703** [comment]
Nice! Thanks man!

**Comment by bluefa1con** [comment]
if you can make a website that would be great
we will be having our builds listed at http://pacman.basketbuild.com/ from the folks at basketbuild

**Comment by blindndumb** [comment]
Anyone working on porting latest PIE features.. Almost all focus is now on vendor..
I will push some commits tonight
![pac_bnd_ico](https://f.cloud.github.com/assets/1883693/248306/6672cc48-8b07-11e2-8d9a-b99eb614791c.png)

Sharing a pic I used in aroma

**Comment by Druboo666** [comment]
nice mod  of the pic

love it

**Comment by bluefa1con** [comment]
@blindndumb we have pie from PA3.10 but it needs updating from PA commits
i merged most of the cm updates if you can update the pie commits

**Comment by OldDroid** [comment]
already working on a website, metaiiica, im also from germany, maybe you should contact me on facebook

**Comment by metaiiica** [comment]
i have installed Wordpress on my Site, i think this is the best option. If any interested for help update, please send me a PN in XDA with your wished Username, your Emailadress and your supported Device. I need also your Username from here to verification. I create a Account so you can easy update your Information for your supported Device.

http://forum.xda-developers.com/member.php?u=4820233

OldDroid i cant send you a request. i found to much from your name... Send me your FB-Link in the PN in XDA^^

**Comment by bluefa1con** [comment]
you guys can take care of site and get it up and running that would be really awesome :)

**Comment by Segfault-Git** [comment]
i develop PAC stats (preview http://galaxy-nexus.org.ua/PACstats/stats.php) app + php. if you made site - tell me. i will add php stats. also i can make theme for wordpress (my theme for joomla http://galaxy-nexus.org.ua)

**Comment by bluefa1con** [comment]
^ looks really awesome mate keep up the good work

**Comment by metaiiica** [comment]
Hi, have a look to the Website, i have created it with Wordpress so any can easy publish your Work.

**Comment by metaiiica** [comment]
Please help update this site.... 

first i need Pictures from all officially Devices with Codename and Devicename... e.g. p990 = LG Optimus Ox/Optimus Speed

**Comment by Papa-Smurf151** [comment]
d2spr = samsung galaxy III sprint variation

what kind of picture of our device are you looking for...a generic one or
one with pacman loaded onto it.

**Comment by szlkiev** [comment]
urushi = Sony Ericsson Xperia Ray

**Comment by szlkiev** [comment]
Picture : gsmarena.com

**Comment by blindndumb** [comment]
saga = HTC Desire S

**Comment by singhdd93** [comment]
coconut - SE Live With Walkman
mango - SE Xperia Mini Pro
satsuma -  SE Xperia Active
smultron - SE Xperia Mini

**Comment by cmartinbaughman** [comment]
Shooter = HTC Evo 3D

**Comment by Druboo666** [comment]
haida=Xperia NEO V
picture= gsm Arena

**Comment by bluefa1con** [comment]
there are 2 variants of galaxy s2 so include the code name as the name on site
i9100
i9100G

for nexus devices
mako=Nexus 4
grouper(soon to be supported)=Nexus 7

**Comment by oerner** [comment]
crespo = nexus s
p920 = lg optimus 3d
p970 = lg optimus black

**Comment by jaydub82** [comment]
t0lte= Note 2 (sprint, att, and tmobile)
Hercules= Galaxy S II (t-mobile)

**Comment by Segfault-Git** [comment]
maguro = Galaxy Nexus (EU)

**Comment by gs2usr** [comment]
Skyrocket = at&t Samsung galaxy S2 LTE i727

Website is looking good by the way.

**Comment by metaiiica** [comment]
thank you for the big replay. Its very helpful for me... At Weekend i have free (free is a privileged Word in the Moment^^) and can any do..

My Idea is following: Any Dev was actually make a Build can help me in the Website. So all can register... you send me only your emailadress and your wished Username and to verification your Username here. What can you do: You set a inlineframe to the Orginal-Thead in XDA from your 
Second all Dev was P.A.C build write a little text from your device what you use and for what you build.
At last i would make to all builded devices a Pic and linked to your created Post.
Interested??

when any have a idea to Layout, Pics or other to the Website, contact me in XDA... 

all for one, one for all :dancers:

**Comment by Wechy77** [comment]
urushi = Xperia ray
Great idea

**Comment by gs2usr** [comment]
i have a suggestion, on the Devices' drop down list can it be made so that per say after 15 devices to start a new column on the side, like this for example: 
![image](https://f.cloud.github.com/assets/2029207/266968/bd641e90-8e49-11e2-95ef-2617bb9e684a.png)

(first place i could think of for the example, lol)
everytime i scroll down to try and select a device the column disappears so it has to be clicked again.

**Comment by blindndumb** [comment]
Make a page of all devices sorted alphabetically , with an image and link to downloads and xda thread below it..
As Cyanogen and MIUI has ..

**Comment by metaiiica** [comment]
The Drop-downlist is only the Categories... i would make seperate Sites for all Devices. The Categories is for Posts only

**Comment by blindndumb** [comment]
Cool , Take your time .. No Hurry !

**Comment by atrus5** [comment]
ville = HTC One S

**Comment by klin1344** [comment]
d2tmo = US T-Mobile Galaxy S3
d2att = US AT&T Galaxy S3
d2vzw = US Verizon Galaxy S3

**Comment by bluefa1con** [comment]
a web designer pm'ed me on xda
he has a server and he is interested in making us a website
i asked him to do it :)

**Comment by metaiiica** [comment]
Why would you use a new Server and website when we have a Site? We can use mine. I have 5 GB Space. 

I do my best so we have a good representative Site...

**Comment by szlkiev** [comment]
Now, its getting more confusing
metaiiica bought a domain http://pac-man-rom.de
nukeAOSP is working on pac statistic which i asked him, but still link it to his personal domain.
OldDroid came up with get.pac and PulseDroid as the web designer.
bluefa1con also got offer from someone who is a web designer and has a server to host pacman website for free, 

and i believe maybe sooner or later there will be another guys offering something with his own pacman website, themes, new logo, wallpapers & everything "with his own taste".
These are good, because it means PAC-man rom already in the heart amongst us, many peoples want to contribute something, be part of it and to make pacman better & better, i really appreciate it.
But one thing for you guys to be kept in mind, this pacman thing is not my personal project anymore, its belong to the community, so even i started all of this, doesn't mean i have rights to decide everything, also means if some one come up with something he can't straight away proclaiming it to become official, we need some one else agreed to make it official, not everyone has the same taste, but with a vote we can decide it, we are living in a democracy world aren't we?

So the main purpose i write this comment is to helping us by moderating these enthusiasm, i might ask bluefa1con for helping me with this moderating thing, will you blue?

so, here are my personal opinion,
1. I like OldDroid's get.pac idea which is like get.cm, its a simple url & easy to remember but also already represent pacman rom by the url address
2. Even metaiiica bought that domain & starting working on pacman website by his own, doesn't mean its already a pacman official website, but since he already gave away some money to bought that domain, i think its a better idea to keep that web domain address if he can change it from "pac-man-rom.de" to "get.pac"
3. About design, i've already know OldDroid's friend, PulseDroid http://www.thyme2serve.co.za/pulsedroid/ He is a true a graphic designer and i admiring his work, his works are amazing, he got class, he also ever made a signature banner for us, but is he already decided to become pacman's designer? no one ever vote him yet,
lets see what bluefa1con's guy's work, can you link his work blue?
4. Once this pacman official webpage address is decided, no more new web hosting offer, so nukeAOSP can start merging the pac stat to it, also bluefa1con buildbot output can be link there too. Plus if some one new want to make some enchantment about the webpage, he may contact directly to the current men in charge and work together as a webmaster team.

so this is what we need to vote
1. url address, pac-man-rom.de or get.pac
2. who is the official web designer for pacman, metaiiica, pulsedroid or bluefa1con's friend (after he can show us his work)

**Comment by blindndumb** [comment]
URL - get.pac .. Its best ..
Designer - I like pulsedroid's work , However we cant forget metaiica's contribution .. May be they can work

**Comment by bluefa1con** [comment]
yeah @szlkiev i can moderate this
get.pac is excellent
the website is not decided yet lets wait for what each of them come up with and than we can install the one which is the best as the mainsite
the guy who messaged me doesnt have much posts on xda but his message was
"yes i propose you a web site ... what do you need ? tell me 
i'm using joomla regulary, i have acces to rockettheme.com and yootheme.com (joomla template and extensions)

 i have a server and i can make you a site ..."
as far as i have worked with websites (somewhat a year back) rockettheme and yootheme have hundreds of professional themes thats why i liked his idea
the pulse droid site is also using a very common theme i saw

**Comment by singhdd93** [comment]
My vote for URL goes to get.pac
Regarding web designer - Anyone can work or all together. It doesnt matter as long as we have a good website.

**Comment by metaiiica** [comment]
ok you need not my site? so you do what you want, but without me! Im very pissed!

**Comment by bluefa1con** [comment]
@metaiiica we are not doing something without you
infact we are not doing anything at all, when we are offered by actual web designers to make a website its in the best interest to let the pro handle the job
besides the best website will be chosen as PAC default website, i dont have much free time other wise i made some joomla sites too in the past
when you are working in a team there is no "ME" in a team, whats in the best interest of the project is done 
hope you understand

**Comment by szlkiev** [comment]
metaiiica, you misunderstood, first please drop the attitude will you?

If most of us here want a different url name, all you want to do is just contact your hosting provider and ask just to change the url name but still the same domain ip address.
I do not propose to change to another server. Once the url name changed as we all decided, then your website will become our official website and we will spread it all over xda, and you still become the lead webmaster.

2nd of things, your current front page is still plain, we definitely need someone to helping you on the graphic section, you are good at web programming but it still need more theming,  that is why in propose someone else who has strong skill in graphic to work together with you.

So like my pacman project its not my personal project anymore, so does your personal website, its not yours anymore, it belongs to pacman team now if you want to make it official, and you will accept several peoples to working together with you, but not me because I don't have the skill.

**Comment by metaiiica** [comment]
its make only confused for the user when we any make lots of sites. My opinion was we concentrate all to a one site while that helps our user was use our builds. 
When any can make a website (layout or what ever), contact me, i install the base, give the Webdesigner permission so he can work on this site. When we not use Wordpress is ok, can use Joomla too or what the webdesigner use.

My Idea: As Base my Site, next in this we integrate Github, get-pac, Buildbox and all what we need. 

So is all in one... 

Wordpress and Joomla can work with all from us, all register and can help.... This was my idea why we can use my site. Next i think the Domainname is representative enough

**Comment by bluefa1con** [comment]
the problem is the domain is dutch and the project is global plus get.pac looks really good or we can use names like pacrom.com or pacmanrom.com 
the many versions of sites wont be online they will be only to preview and choose the best, the user wont have to deal with them
the buildbox people are also improving their services, they are working on their own OTA app so we will be able to drop goo.im

**Comment by szlkiev** [comment]
You clearly misunderstood me once again,
My intention is to PREVENT other website offer from others, once YOUR WEBSITE is pointed to be our OFFICIAL one.
In term you change the url name to the url name that we all like.

Once its done it will belong to pacman team, no more "my or mine", it will be "our & ours".
But you still in charge in maintaining & leading it.

Ps
My be its my bad English that made you always misunderstood me, sorry for that.

**Comment by metaiiica** [comment]
lol szlkiev, do you mean my english is better? xD

mhhh changing the name is a big problem, dont know how can do that.. I think my provider does not support that.

**Comment by Nick0703** [comment]
Sorry I was M.I.A for the past few days but the
captivatemtd = Samsung Galaxy S Captivate
p3100 = Samsung Galaxy Tab 2 7.0 (GSM version)
p3110 = Samsung Galaxy Tab 2 7.0 (Wifi version)
p5100 = Samsung Galaxy Tab 2 10.1 (GSM version)
p5110 = Samsung Galaxy Tab 2 10.1 (Wifi version)

**Comment by singhdd93** [comment]
Hey guys pacmanrom.com is available for sale. I can get this domain for 10$/year.

**Comment by metaiiica** [comment]
10$ is a good price. But what have you for features??

we need more TLD^^
pac-man-rom.p990
pac-man-rom.gio
pac-man-rom.crespo
pac-man-rom.captivatemtd
...
rofl

**Comment by PulseDroid** [comment]
Hello, I heard my name a few times here, metaiiica, don't be pissed =P 

I don't care, you can do it lol. I was thinking that I was helping you guys but lol you guys are fighting over who does what xD

Msg me if you want my help otherwise I'll leave, lol no need to be pissed.

**Comment by singhdd93** [comment]
What features do you mean ?
that is price of only a domian without web hosting.

**Comment by PulseDroid** [comment]
Think he means, like how many domains can you redirect, how many add on domains can you have, if traffic can be monitored etc.

EG:

google.com  
mail.google.com
translate.google.com 

etc..

Also, TLD (Top Level Domain) -> .com etc..

Or maybe, if it supports stuff like fancy quotes etc.

**Comment by singhdd93** [comment]
http://hosting.brandtoast.com/content.php?action=free_services
The above link is the link of domain provider. He is my dad's friend

Also I have one other domain bought from him and have almost 15 subdomains running on my hosting account at hostmonster.

**Comment by PulseDroid** [comment]
If you need it, I can get a 100GB uncapped bandwidth Server free...

**Comment by szlkiev** [comment]
@metaiiica, have you contacted your domain hosting service company?
Can the url name be changed to get.pac?

**Comment by metaiiica** [comment]
i ask it, but i think they answered, i must register new -.-

**Comment by szlkiev** [comment]
Oh too bad, dont buy another one then, lets ask pulsedroid to make a new n free one, then move your web content there, what do you think?

**Comment by metaiiica** [comment]
that a good idea. Contact me on XDA :D

**Comment by bluefa1con** [comment]
@metaiiica can u install a private forum on your domain that only the team has access to?
things like these should be discussed in private
we cant have everything public it gives out too much info
for example if some one knows our host and that host is known to have a vulnerability we can be under potential threat

**Comment by metaiiica** [comment]
yes i can do that when i come home from work at 21:00

What frorum-script would you haved install?? WBB or something other?

**Comment by bluefa1con** [comment]
anyone thats compatible with tapatalk

**Comment by metaiiica** [comment]
So i have created a forum. I have no access for all, only Admin, Mods and a created Group Github have access. 

http://pac-man-rom.de/dsfffddgdf/

all from here can register, but access must given to me. Please use the same emailadress was you use here... If any know how phpbb works, please send me a PN in XDA i give you Admin Access. Rest come in Group Github.

**Comment by metaiiica** [comment]
Tapatalk is supported too

**Comment by bluefa1con** [comment]
i got a offer from the build bot people, they are willing to give us a full featured public forum and a private forum for team discussion
what do u guys say?

**Comment by metaiiica** [comment]
ähm, is that a joke? For what spent i time to create a forum? You ask me to install a Forum, i do it and what now?

lol?

**Comment by vertigo2012** [comment]
Sounds good to me...

**Comment by Papa-Smurf151** [comment]
Lol

**Comment by bluefa1con** [comment]
@metaiiica thats why i am asking here they are professional people already running forums
i want the teams view on it
we can have forums like cm and aokp does
think about it the people at basketbuild.com provide us with download hosting,OTA service, forums, buildbot
i have made different websites many times that i just had to ditch later for better solutions

**Comment by metaiiica** [comment]
@bluefa1con The forum was i installed is secret, when all registered, i install a htaccess Login, so can nothing without access read. And its can use for public and use for Team only. can give different permission

But you destroy all my motivation for work in the Team.... I would lots of do for the team... but your new crap demotivate me again... 

just my 5 cents

**Comment by bluefa1con** [comment]
i am trying to get pacman huge....giving it more of a organization appeal, android projects come up and die only some get to live and see sponcerships from professional companies
plus you are thinking short term ok if we use your forum keep in mind that you will have to take care of the php databases, backups and upgrades
they already have a network for it that does that plus i presented an offer i got from them nothing is decided
ok you want us to use yours i am registering my username will be bluefa1con
no one's effort is being wasted
you have no idea how much time i spent negotiating with different people to help us
goo.im assured me of buildbox and gave me contact for gtalk but they kept ignoring me when i actually asked them to deliver what they promised
we are a team and we discuss together thats why i came here to talk rather than saying yes to him

got this wheni signed up
No data received
Unable to load the webpage because the server sent no data.
Here are some suggestions:
Reload this webpage later.
Error 324 (net::ERR_EMPTY_RESPONSE): The server closed the connection without sending any data.

**Comment by metaiiica** [comment]
mhhhh my site is not loading??

**Comment by bluefa1con** [comment]
made a account again approve it :)

**Comment by blindndumb** [comment]
I assume every one one of us is confused with this website thing..
First of all who is going to make. I second what bluefa1con said in previous post.
Seriously , wordpress for PAC-man , Common give it a good look atleast , then further keep adding features and all..
What about get.pac ??

**Comment by Segfault-Git** [comment]
hi. 
1) i can make wordpress theme (my work. spend 2 hours http://galaxy-nexus.org.ua). I do not like wordpress. prefer joomla. many more advantages and Wordpress designed for blog, but not site.
2) i have good host for sites (try my site)
3) if you want PacStats - contact me (ICQ 492086694 answer 4, fly03043090@gmail.com). App ready. I need ftp access and parameters of your hosting

**Comment by metaiiica** [comment]
we can leave to Joomla, this is not a problem:)

Please wait to Sunday, i have the next day small time, must hard work... :( But then i can install a base of Joomla and we can work  at the site... i contact you when i have time at ICQ

**Comment by metaiiica** [comment]
Important: Please dont forget all to register to the forum. When all registered, i can make a intern Section for us only.

**Comment by KBizzle** [comment]
I am way behind. Where is the forum located?

**Comment by KBizzle** [comment]
Never mind. I'm signed up.

**Comment by singhdd93** [comment]
Just signed up

**Comment by metaiiica** [comment]
all was registered are activated and moved to Group Github

**Comment by jaydub82** [comment]
metaiiica,
I have registered
Username: jaydub82

**Comment by Nick0703** [comment]
I'm trying to register but I'm getting error 404 not found.

**Comment by KBizzle** [comment]
Here you go. http://pac-man-rom.de/dsfffddgdf/

**Comment by Nick0703** [comment]
Thanks, I registered.

Username is the same as my github account. Nick0703

**Comment by metaiiica** [comment]
all done

But unfortunately missing a few where have to register...

**Comment by klin1344** [comment]
I just registered with the same account name as well.  klin1344

Thanks.

**Comment by bluefa1con** [comment]
posted some detail from host on the internal forum
have a look :)

**Comment by oerner** [comment]
registered name is berni987654321

**Comment by Segfault-Git** [comment]
registered name jack_nuclear

**Comment by Segfault-Git** [comment]
metaiiica answer me about pac-stat

**Comment by metaiiica** [comment]
we can use P.A.C. Stat give you the permission in the next days :)

rest all activated and moved to group github

**Comment by jamieg71** [comment]
My apologies for being away for so long, I have been working non stop.
Registered name jamieg71
Devices--
jewel = Sprint HTC Evo 4G LTE
evita = AT&T HTC One X

I am trying to catch up on all that has transpired, please let me know if I
am missing anything I need to do. The build bot is great idea, should make
our lives a little easier once set up.

**Comment by jamieg71** [comment]
Oh, and also I vote for get.pac!

**Comment by klin1344** [comment]
Hmmm I still can't log in.  I registered at least more than a week ago but I never got an email that my account was approved by an admin.

**Comment by IvanBrazza** [comment]
What would you all say to using gerrit to manage the code for the repos? If you don't know gerrit is the software that runs review.cyanogenmod.org. So if PAC started using it then it could be easier to manage code submissions, instead of via pull requests. Only specific people can be set to allow code submissions to be merged and they're all in one place that can be done on the website when that's decided. I can set it all up for you, but the slight problem is I'd need SSH access to the server where it's running, including sudo. Sudo is needed so I can modify the apache configs to get the application running on port 80.

**Comment by bluefa1con** [comment]
thats just extra work for us to manage another site
we are even close to cm size we can manage  pacman via pull requests easier for us to track
besides only a few people submit framework patches rest are just vendor updates
if we have more contributors maybe in future we can do it but not right now

**Comment by bluefa1con** [comment]
approve Papa smurf151 and Basketthis :)

**Comment by Papa-Smurf151** [comment]
Its not letting me log in. Did I register the wrong name.

Papa Smurf151

**Comment by metaiiica** [comment]
both Accounts now activated and moved to group github

**Comment by Papa-Smurf151** [comment]
And I'm in. Thanks

**Comment by metaiiica** [comment]
bluefa1con i have you give Admin-rights.

**Comment by Papa-Smurf151** [comment]
I can help with admin stuff if u ever need help. I'm a moderator on xda as
well

**Comment by metaiiica** [comment]
ok know that, have give you adminrights also. Can you setting up the Forum a little bit? I have no time to do that, must work hard in the moment...

A good Idea is we can use this Forum for public use too. we can have a secret and open and public Forum for Support for problems, faq or other related things.... What you mean?

When public, i move it to a better folder such as pack.man-rom.de/forum/ instead pac-man-rom.de/dsfffddgdf/

**Comment by Papa-Smurf151** [comment]
BTW what the label under tapatalk.apk to view the forum from within the apk
instead if a browser

**Comment by Papa-Smurf151** [comment]
Yes I'm mobile for the next day or so but I can help getting the forum set
up for open and private rooms.

**Comment by metaiiica** [comment]
i dont know how i can setup for Tapatalk... hope bluefa1con can setup correctly....

**Comment by cmartinbaughman** [comment]
I'd like to do whatever I can to help but I actually thought I registered last week on the new forums however it doesn't seem to think I am registered. Can someone help, I should prob have admin as well, I am the device maintainer for shooter, shooter, and shootervm.  Thanks much!

**Comment by klin1344** [comment]
metaiiica- please activate my account on the forum.  I registered over 3 weeks ago and I still cannot log in...

klin1344

**Comment by metaiiica** [comment]
I have activated as you registered. Now i have reactivated, so you i hope you can log in...

**Comment by jeroenqui** [comment]
please activate me too: username: jeroenqui

**Comment by metaiiica** [comment]
done

**Comment by Grarak** [comment]
@metaiiica me too please 
username: Grarak

**Comment by metaiiica** [comment]
Grarak, you are activated. ( as you registered)

**Comment by klin1344** [comment]
Thank you, I can finally log in now. :)

**Comment by Papa-Smurf151** [comment]
I have made some large changes to the structure of the forum site. Everyone
please login and see the changes.  Invite your friends and then have them
join the site.

**Comment by Nick0703** [comment]
@Papa-Smurf151 It looks more organized now, thanks!

**Comment by Papa-Smurf151** [comment]
Not even close to being done but its a start

**Comment by metaiiica** [comment]
In the next days i would like move the Forum to a serious location eg. http://pac-man-rom.de/forum

**Comment by Papa-Smurf151** [comment]
I agree...Metallica please see my pm and thread in admin forum.

**Comment by metaiiica** [comment]
morning i have a little bit time(after a long time^^) to answer and do somethings.

**Comment by tdm** [comment]
Hi, I'm a new member.  I'll be maintaining the LG iproj devices (P930/SU640/VS920).  Registered in forum as user tdm.

**Comment by Papa-Smurf151** [comment]
Its not showing me a tmd as a user name on forum. Did u complete
registration

**Comment by tdm** [comment]
It's tdm not tmd.  I'm logged in now (http://pac-man-rom.de/dsfffddgdf)

**Comment by Papa-Smurf151** [comment]
Tdm gotcha down as maintainer in forum now

**Comment by metaiiica** [comment]
IMPORTANT! 
Today i move the Forum to a new Location. Do it at 22:00 MEZ From this time on can forum be offline or can corrupt. When finish, would inform here at the Github Site:)

**Comment by Papa-Smurf151** [comment]
Metallica please contact me asap. I've tried on forum and through pm and
email.

**Comment by metaiiica** [comment]
So, moving was successfull!

New URL now http://pac-man-rom.de/forum/

**Comment by tdm** [comment]
Thought you might want to know: the forum seems to be getting a lot of SQL timeouts today.

**Comment by Papa-Smurf151** [comment]
We r in process of talking to server hosts. Its a problem on their side

**Comment by singhdd93** [comment]
I am unable to open forum website.
Keep getting Genral Error

**Comment by metaiiica** [comment]
So we had big trouble with the forum so we must install all new. A import exist data such as users and other generated corrupt data so we must install all new. when all finish, please all maintainers must register new.

**Comment by Papa-Smurf151** [comment]
Site is back up

please read this thread and if you are not a member then please reregister
and pm me and Ill add you to the maintainer list.  Most of the users have
been restored.

http://pac-man-rom.de/forum/viewtopic.php?f=1&t=16

please read this thread

**Comment by cmartinbaughman** [comment]
Hey PapaSmurf I registered on the site I am a device maintainer for shooter/shootervm/x515m(shooteru) and contributor for the rom. I couldnt figure out how to get Tapatalk to let me pm on the site. Anyway please add me? Thanks much! 
Username: cmbaughman
Email: cmbaughman@live.com

**Comment by Papa-Smurf151** [comment]
I have added u as a maintainer

I deleted you dbl account

Cmartinbaughman

Please visit device maintainer thread for all the fun stuff

**Comment by Segfault-Git** [comment]
metaiiica dont forget about me? Pac stats and so on?

**Comment by Papa-Smurf151** [comment]
Come to forum and start a thread so we can implement

**Comment by metaiiica** [comment]
i had not forget.... 

now i close here, open only here if Forum down or other...

**Comment by cmartinbaughman** [comment]
Hey Papa-Smurf151 thanks much! See you there!

**Comment by Wechy77** [comment]
Forum gives me general error again using pc and chrome. With phone and tapatalk it works.
"General Error
template->_tpl_load_file(): File ./styles/X-Treme/template/index_body_thanks.html does not exist or is empty"

**Comment by Wechy77** [comment]
Fixed
