### ISSUE TITLE
dependencies error

### ISSUE THREAD

**Issue by oerner** [PAC-ROM/android_vendor_pac#64]
hi guys I found a little error,
if there is no local_manifests folder in .repo the dependencies script will give you an error

**Comment by gs2usr** [comment]
What is the error?

**Comment by blindndumb** [comment]
Create a file .repo/local_manifests/roomservice.xml and copy all contents of local_manifests.xml in it.
It will sove

Alternate way :
delete local_manifests directory once..
Run ./build-pac.sh device
ctrc +c after it shows starting compilation
repo sync -j8
It will solve too..

Try first method...
This happens because local_manifests.xml is now changed to roomservice.xml

**Comment by oerner** [comment]
I already solved it that way, 
just wanted to tell it that maybe somebody can make a fix
