### ISSUE TITLE
back button to collapse statusbar

### ISSUE THREAD

**Issue by bluefa1con** [PAC-ROM/android_vendor_pac#80]
looks like one of the recent commits have broken pressing back button to collapse statusbar
please someone have a look into it i am quite busy

**Comment by singhdd93** [comment]
Working for Me on 15th March build. Must have been done after that

**Comment by bluefa1con** [comment]
yeah its one of the commits after the slim bean ports
the only changes to the statusbar after that is the toggle update from PA so i think that is the reason

**Comment by Nick0703** [comment]
I'll take a look at it

**Comment by Nick0703** [comment]
So when in Table UI, the back button collapse the statusbar but when you switch back to phone UI it doesn't work.

**Comment by TheRealChickenlegs** [comment]
Also just noticed that it won't switch to QuickSettings panel if there are no notifications.

**Comment by Nick0703** [comment]
You mean when you pulldown the notifications panel? If it's that then it's normal. Because that option hasn't been merged yet. I'm still working on that.

**Comment by TheRealChickenlegs** [comment]
Yes that's right, weird because that used to happen before or I could just be going crazy! Time for more coffee.

**Comment by bluefa1con** [comment]
hope you can fix it in time i had to delay v22 because of that

**Comment by TheRealChickenlegs** [comment]
I made a new build tonight and reverted the two commits for the QuickSettings Update to see if it restored everything and it did so somewhere in there is the issue. Statusbar collapses fine with back button, switches to QuickSettings if no notifications when pulling the notification panel down (don't know if this only happens on the i9100??) and also turns the screen off with the proximity sensor when in a call (only realised that one tonight before I rebuild without the commits). So much in those two commits I have been going through them too trying to track down the culprit but man there is a lot to go through!! :) I will look at it again tomorrow.

**Comment by Nick0703** [comment]
I'm currently working on a fix for it. Let's hope that I don't get any errors while compiling......

**Comment by metaiiica** [comment]
in the Moment, i test to make a Build with OpenPDroid patched. Before i merge here, is any interested to build with OpenPdroid included? 
When Yes, i need Access to:
android_packages_apps_Mms
android_build
android_frameworks_base

and we need a Repo 
android_frameworks_opt_telephony
android_libcore

i would merge all in same time so no one have a failed build

Or: i make the needed and patched repos in my Githubacc and all can test and make a testbuild.

**Comment by TheRealChickenlegs** [comment]
I maintain the auto_patcher patches for PAC which provides the ability to patch roms. I build with no problems applying the patches locally and removing and cleaning for syncs. I don't really think the patches should be applied against the source repos as I think this could cause problems in the future when cherry-picking and it would make it virtually impossible to upgrade the OpenPdroid patches when new versions are released. Just my 2 cents.

**Comment by metaiiica** [comment]
i have tested Autopatcher, does not work for me. and i find so its better and you must not patch again when finished build....

**Comment by metaiiica** [comment]
Build is completed and success...

**Comment by Nick0703** [comment]
The notifications panel closes when you press the back button?

**Comment by TheRealChickenlegs** [comment]
Auto_patcher definitely works for PAC you just specify openpdroid as the patch and no rom type, I have helped many users from different handsets patch their version of PAC have a look at the thread on xda.

Adding such a massive patch to that many repo's will make it really hard to cherry-pick as it is going to produce a massive amount of conflicts. Have a look at the actual patch files for OpenPdroid in auto_patcher as these are just normal linux patch files with diff information and see how much is modified and added by the patches. Also people trying to cherry-pick anything from the patched PAC repos would find that impossible unless they also have the OpenPdroid framework patched into their source.

Once the patches are saved to the repo other commits are made etc how are you going to be able to easily reverse the patches to apply the new versions? I know that OpenPdroid v1.1 is not far off and as long as there is demand new versions will continue to be produced. 

Don't get me wrong I have nothing against OpenPdroid I have used it since ICS back when svyat first released it, there is no better solution to manage your privacy and application permissions, I just don't think it is a good idea to add it to the PAC source. I have two simple scripts I wrote one applies the patches to my working tree and the other removes the patches and cleans up, doing it locally means its easy to use an updated version and the PAC source remains clean.

**Comment by Nick0703** [comment]
So I've compiled a new build and it didn't fix it. It looks like the problems lies within PA's sources. But one thing caught my eyes was this code. http://pastebin.com/JPmFwAkZ (From the NotificationPanel.java for the table). The NotificationPanel.java for the phone does not has that code in it?

https://github.com/ParanoidAndroid/android_frameworks_base/blob/jellybean/packages/SystemUI/src/com/android/systemui/statusbar/tablet/NotificationPanel.java

**Comment by Nick0703** [comment]
I'm trying to add that code to the NotificationPanel.java (For the phone), I'll report back if it works.

**Comment by Nick0703** [comment]
No success guys. It didn't work......

**Comment by bluefa1con** [comment]
revert the quick settings commit than 
sorry but i want to release v22 and i am holding back because of it
we dont need pdroid in sources, people who want it can use the patcher

**Comment by Nick0703** [comment]
Can someone take a look at the codes for the PhoneStatusBar.java? I think the problem lays in this.

**Comment by metaiiica** [comment]
okay this was just a idea :dancers:

**Comment by Nick0703** [comment]
Well everything else works fine, it's just the back button......

**Comment by TheRealChickenlegs** [comment]
Just had a successful build with a possible fix after correcting some build errors, I will do a full wipe and clean install and report back shortly.

**Comment by Nick0703** [comment]
Alright thanks! I'll wait for you report.

**Comment by TheRealChickenlegs** [comment]
No go that time but re-compiling checked the PhoneStatusBar.java again against a version prior to the initial QuickSettings commit and noticed I had somehow missed three things! DOH! 2 x onClickListeners & skipToSettingsPanel() function. Fingers crossed this sorts it now. I have to go out in 45 minutes so I am hoping the build finishes before then so I can check and commit, if time runs out as soon as I get back I will let you know & commit if its all good.

**Comment by gs2usr** [comment]
i just finished a build with a fix, and it works. Im putting together the commit for it and will push it in a few.

**Comment by gs2usr** [comment]
Its done. could someone else confirm the fix works before we close this issue. thanks
